fix implicitly nullable via default value null for PHP-8.4
hamcrest/hamcrest-php pull request #85
Opened 2024-12-05 17:17 UTC by txdFabio

use of explicit nullable type for php-8.4 compatibility

2024-12-05 17:50 UTC, aik099 requested changes
This change breaks support for PHP versions below PHP 7.2.

2024-12-05 18:01 UTC, txdFabio commented
you're right... can we change composer requirements to supporto only newer versions? Do I have to submit another PR?

2024-12-06 16:49 UTC, aik099 commented
@davedevelopment, should we raise the minimum supported PHP version of the library (e.g., to PHP 7.2) to allow changes like the one proposed in this PR to work on PHP 8.4?

2025-02-18 12:36 UTC, PNardman commented
+ 1 already waiting for this. 👍

2025-03-05 10:30 UTC, PNardman commented
Any update on when this could be merged? Updated?

2025-03-05 11:50 UTC, aik099 commented
> Any update on when this could be merged? Updated?

@PNardma , no updates.

@davedevelopment , ping.

2025-04-07 09:26 UTC, PNardman commented
Still no update. 😢

2025-04-29 10:27 UTC, davedevelopment commented
I'm sorry, I've been away from Hamcrest for some time and completely forgot about my responsibilities here. Generally, I'd say yes, 7.2 is very old and they can always version pin.

2025-04-29 12:07 UTC, aik099 commented
@davedevelopment , then here are the next steps:

1. create another PR that will set a minimum compatible PHP version to PHP 7.2 (or even PHP 7.4)
2. make a release
3. rebase & merge this PR

.

2025-04-29 12:50 UTC, davedevelopment commented
Opened #87

2025-04-29 18:13 UTC, merged

2025-04-29 22:29 UTC, txdFabio commented
I've seen the 2.1.0 release which remove older php constraints, but - while it's merged to master - it doesn't include the implicit nullable fix, is there anything else we need to do?